import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const metadata = {
//   title: "Milikiyat - Premium Real Estate in Dubai",
//   description: "Explore luxurious properties, villas, and apartments in Dubai with Milikiyat Real Estate.",
// };

export const metadata = {
  title: "Milikiyat - Premium Real Estate in Dubai",
  description: "Explore luxurious properties, villas, and apartments in Dubai with Milikiyat Real Estate.",
  icons: {
    icon: "/favicon.ico",   // main favicon
    apple: "/favicon.png",  // optional for Apple devices
  },
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        
        {children}
        <Footer/>
      </body>
    </html>
  );
}


